#!/usr/bin/pwsh
#
# script to reset OneView backend
#Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false
$servername = "vcenterapp65.hp.local"
$username = "Administrator@vsphere.local"
$password = "P@ssw0rd"
#Connect to Vcenter appliance :
connect-viserver $servername -username $username -password $password
#Reverting HPE_OneView_DCS_5.30_simu1
#Set Vm name as variable
$vmsimu1 = "HPE_OneView_DCS_5.30_Simu1"
#Get snapshot name from VMs
$snap1 = Get-Snapshot -VM $vmsimu1
#Revert to snapshot
#Reverting snap $snap1"
Set-VM -VM $vmsimu1 -SnapShot $snap1 -Confirm:$false
#Reverting HPE_OneView_DCS_5.30_simu2
#Set Vm name as variable
$vmsimu2 = "HPE_OneView_DCS_5.30_Simu2"
#Get snapshot name from VMs
$snap2 = Get-Snapshot -VM $vmsimu2
#Revert to snapshot
#Reverting snap $snap2"
Set-VM -VM $vmsimu2 -SnapShot $snap2 -Confirm:$false
exit
