# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.synced_folder './', '/vagrant', type: 'rsync'
  #config.vm.synced_folder './', '/vagrant', type: 'nfs'
  # Private management network for DHCP naming and adressing
  config.vm.provider :libvirt do |domain|
    domain.management_network_name = "wodnet"
    domain.management_network_address = "10.1.0.0/24"
    domain.management_network_mode = "route"
  end

  config.vm.define "wod-be-centos-7" do |wodbecentos7|
    wodbecentos7.vm.box = "generic/centos7"
    wodbecentos7.vm.hostname = "wod-be-centos-7.wodnet.local"
    #wodbecentos7.vm.network  "private_network", ip: "192.168.200.10"
    wodbecentos7.vm.network "forwarded_port", guest: 8000, host: 8010
  end
  config.vm.define "wodbec7" do |wodbecentos7|
    wodbecentos7.vm.box = "generic/centos7"
    wodbecentos7.vm.hostname = "wodbec7.wodnet.local"
    #wodbecentos7.vm.network  "private_network", ip: "192.168.200.10"
    wodbecentos7.vm.network "forwarded_port", guest: 8000, host: 8010
  end
  config.vm.define "wod-fe-centos-7" do |wodfecentos7|
    wodfecentos7.vm.box = "generic/centos7"
    wodfecentos7.vm.hostname = "wod-fe-centos-7.wodnet.local"
    #wodfecentos7.vm.network  "private_network", ip: "192.168.200.10"
    wodfecentos7.vm.network "forwarded_port", guest: 8000, host: 8011
  end
  config.vm.define "wod-fe-ubuntu-20.04" do |wodfeubuntu2004|
    wodfeubuntu2004.vm.box = "generic/ubuntu2004"
    wodfeubuntu2004.vm.hostname = "wod-fe-ubuntu-2004.wodnet.local"
    #wodfeubuntu2004.vm.network  "private_network", ip: "192.168.200.20"
    wodfeubuntu2004.vm.network "forwarded_port", guest: 8000, host: 8012
  end
  config.vm.define "wod-be-ubuntu-20.04" do |wodbeubuntu2004|
    wodbeubuntu2004.vm.box = "generic/ubuntu2004"
    wodbeubuntu2004.vm.hostname = "wod-be-ubuntu-2004.wodnet.local"
    #wodbeubuntu2004.vm.network  "private_network", ip: "192.168.200.20"
    wodbeubuntu2004.vm.network "forwarded_port", guest: 8000, host: 8020
  end
  config.vm.define "wod-api-ubuntu-20.04" do |wodapiubuntu2004|
    wodapiubuntu2004.vm.box = "generic/ubuntu2004"
    wodapiubuntu2004.vm.hostname = "wod-api-ubuntu-2004.wodnet.local"
    wodapiubuntu2004.vm.network "forwarded_port", guest: 8000, host: 8021
  end
  #ubuntu2004.vm.provider = "libvirt"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
